image: registry.hub.docker.com/cmssw/el8:x86_64

stages:
  - setup
  - test
  - deploy

.setup_script: &setup_script
  - cat /etc/redhat-release
  - source setup.sh

setup:
  stage: setup
  tags:
    - cvmfs
  rules:
    - when: manual
  script:
    - *setup_script

variables:
  PREPIDS: |
    Run3Summer22wmLHEGS
    Run3Summer22EEwmLHEGS
    Run3Summer23wmLHEGS
    Run3Summer23BPixwmLHEGS
    RunIII2024Summer24wmLHEGS
    RunIISummer20UL16GEN
    RunIISummer20UL18wmLHEGEN
  CHAINS: |
    Run3Summer22wmLHEGS-Run3Summer22NanoAODv12
    Run3Summer22EEwmLHEGS-Run3Summer22EENanoAODv12
    Run3Summer23wmLHEGS-Run3Summer23NanoAODv12
    Run3Summer23BPixwmLHEGS-Run3Summer23BPixNanoAODv12
  RUNS: |
    Run3Summer22wmLHEGEN                              
    Run3Summer22wmLHENanoGEN                          
    Run3Summer22wmLHEGS-Run3Summer22NanoAODv12        

.test_getChains: &test_getChains
  - for PREPID in $PREPIDS; do ./getChains.py data/prepids/${PREPID}.json; done

test-getChains:
  stage: test
  tags:
    - cvmfs
  rules:
    - when: always
  script:
    - *setup_script
    - *test_getChains

.test_getPileups: &test_getPileups
  - for CHAIN in $CHAINS; do ./getPileup.py -c data/chains/chain_${CHAIN}.json; done

test-getPileups:
  stage: test
  tags:
    - cvmfs
  rules:
    - when: always
  script:
    - *setup_script
    - *test_getPileups

.deploy_cleanData: &deploy_cleanData
  - ls -alh data/chains/
  - ls -alh data/pileups/
  - for CHAIN in $CHAINS; do rm data/chains/chain_${CHAIN}.json; done
  - for CHAIN in $CHAINS; do rm data/pileups/chain_${CHAIN}.txt; done
  - ls -alh data/chains/
  - ls -alh data/pileups/

.deploy_tarRepo: &deploy_tarRepo
    - ls -LR * > deploy.log  
    - cd ../
    - tar -czf sample_factory.tgz sample_factory
    - cd sample_factory

deploy:
  stage: deploy
  tags:
    - cvmfs
  rules:
    - when: never
    - if: $CI_COMMIT_TAG
  script:
    - *setup_script
    - *deploy_cleanData
    - *test_getChains
    - *test_getPileups
    - *deploy_tarRepo
    - mv ../sample_factory.tgz ./sample_factory_${CI_COMMIT_TAG}.tgz
  artifacts:
    paths:
      - sample_factory_${CI_COMMIT_TAG}.tgz
    expire_in: 12 months
